<?php
session_start();
  //initialize cart if not set or is unset
if(!isset($_SESSION['cart'])){
  $_SESSION['cart'] = array();
}

  //unset qunatity
unset($_SESSION['qty_array']);
include 'dbconnect.php';

?>
<!DOCTYPE html>
<html lang="en" style="background-color:#feffd7; border-bottom:none;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, viewport-fit=cover, shrink-to-fit=no">
    <meta name="description" content="SORONG MARKET LAPAK DAGANG SORONG">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="theme-color" content="#100DD1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <title>SORONG MARKET</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&amp;display=swap">
    <!-- Favicon-->
    <link rel="icon" href="logo.png">
    <!-- Apple Touch Icon-->
    <!-- CSS Libraries-->
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/owl.carousel.min.css">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link rel="stylesheet" href="css/default/lineicons.min.css">
    <!-- Stylesheet-->
    <link rel="stylesheet" href="style.css">
    
  </head>
  <body style="background-color:#feffd7; border-bottom:none;">
 <style type="text/css">
 .kk {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      z-index: 9999;
      background-color: #fff;
    }
    .kk .loading {
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%,-50%);
      font: 14px arial;
    }
   .puff-in-center {
  -webkit-animation: puff-in-center 1.1s cubic-bezier(0.470, 0.000, 0.745, 0.715) infinite both;
          animation: puff-in-center 1.1s cubic-bezier(0.470, 0.000, 0.745, 0.715) infinite both;
}/* ----------------------------------------------
 * Generated by Animista on 2022-1-20 23:22:40
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation puff-in-center
 * ----------------------------------------
 */
@-webkit-keyframes puff-in-center {
  0% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes puff-in-center {
  0% {
    -webkit-transform: scale(2);
            transform: scale(2);
    -webkit-filter: blur(4px);
            filter: blur(4px);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(1);
            transform: scale(1);
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

 </style>     <script src="http://code.jquery.com/jquery-2.2.1.min.js"></script>

    <div class="kk">
      <div class="loading">
        <img class="puff-in-center" style="width:200px;"src="logo.png">
      </div>
    </div>
    <script>
     $(document).ready(function(){
      $(".kk").delay(110).fadeOut(2500);
    })

    </script>
   
    <!-- Header Area-->
    <div class="header-area" style="background-color: #1A1423;"id="headerArea">
      <div class="container h-100 d-flex align-items-center justify-content-between">
        <!-- Logo Wrapper-->
        <div class="logo-wrapper"><a href="home.html"><img  style="height:40px;" src="logo.png" alt=""></a></div>
        <!-- Search Form-->
        <div class="top-search-form">
          <form action="cari.php" method="post">
            <input class="form-control" type="search" name="Search" placeholder="CARI PRODUK !!">
            <button type="submit"><i class="fa fa-search"></i></button>
          </form>
        </div>
        <!-- Navbar Toggler-->
        <div class="suha-navbar-toggler d-flex flex-wrap" id="suhaNavbarToggler" style="visibility: none;" ></div>
      </div>
    </div>
    <!-- Sidenav Black Overlay-->
    
    <!-- Side Nav Wrapper-->
 
     
    <!-- PWA Install Alert-->
   
    <div class="page-content-wrapper">
      <!-- Button trigger modal -->


<!-- Modal -->

      <!-- Product Catagories-->
      <div class="product-catagories-wrapper py-3">
        <div class="container">
          <div class="section-heading">
            <h6>KATEGORI PRODUK</h6>
          </div>
          <div class="product-catagory-wrap">
            <div class="row g-3">
         
            <?php 
                            $kat=mysqli_query($conn,"SELECT * from kategori order by idkategori ASC");
                            while($p=mysqli_fetch_array($kat)){

                              ?>
                                                                 
                          
              <div class="col-4">
                <div class="card catagory-card">
                  <div class="card-body"><a href="kategori.php?idkategori=<?php echo $p['idkategori'] ?>"><span><?php echo $p['namakategori'] ?></span></a></div>
                </div>
              </div>
               <?php
                                  }
                            ?>

          </div>
        </div>
      </div>
      
      <!-- Top Products-->
      <div class="top-products-area clearfix py-3">
        <div class="container">
          
          <div class="row g-3">
           <?php 
                      $brgs=mysqli_query($conn,"SELECT * from produk order by idproduk ASC");
                      $no=1;
                      while($p=mysqli_fetch_array($brgs)){

                        ?>
            <!-- Single Top Product Card-->
            <div class="col-6 col-md-4 col-lg-3">
              <div class="card top-product-card">
                <div style="height:350px;" class="card-body"><a class="wishlist-btn" href="#"></a><a class="product-thumbnail d-block" ><img class="mb-2" src="<?php echo $p['gambar']?>" alt=""></a><a style="margin-bottom:2.25rem;" class="product-title d-block" ><?php echo $p['namaproduk'] ?></a>
                  <p class="sale-price">Rp<?php echo number_format($p['hargaafter']) ?><span>Rp<?php echo number_format($p['hargabefore']) ?></span></p>
                  <div class="product-rating"><i><button type="button"  class="rounded-pill bg-success text-light border-dark"  data-bs-toggle="modal" data-bs-target="#exampleModal<?php echo $p['idproduk'] ?>">&nbsp;&nbsp;Detail Produk&nbsp;&nbsp;
</button></i></div><a class="btn btn-success btn-sm" href="add.php?id=<?php echo $p['idproduk']; ?>"><i class="lni lni-plus"></i></a>
                </div>
              </div>
            </div>
<div class="modal fade" id="exampleModal<?php echo $p['idproduk'] ?>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">DETAIL PRODUK</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <center><img class="mb-2 rounded" style="width:200px;" src="<?php echo $p['gambar']?>" alt=""><table class="table"></center>

    <tr>
     
      <th scope="col" colspan="4"><center><h1><?php echo $p['namaproduk'] ?></h1></center></th>
    </tr>
  
  <tbody>
    <tr>
      <th scope="row" style="color: #6C5A49;"><?php echo $p['deskripsi']?></th>
    </tr>
    
    <tr>

    </tr>
  </tbody>
</table> <font style="font-size:25px;">HARGA Rp<?php echo number_format($p['hargaafter']) ?></font>
      </div>
      <div class="modal-footer">
        <a href="add.php?id=<?php echo $p['idproduk']; ?>" class="btn btn-primary">Masukan Keranjang</a>
      </div>
    </div>
  </div>
</div>
<?php
                      }
                ?>
                
          </div>
        </div>
      </div>
     
      <!-- Weekly Best Sellers-->
  
      <!-- Discount Coupon Card-->
   
      <!-- Featured Products Wrapper-->
      
    </div>
    <!-- Internet Connection Status-->
    <div class="internet-connection-status" id="internetStatus"></div>
    <!-- Footer Nav-->
    <div class="footer-nav-area" style="background-color: #1A1423;" id="footerNav">
      <div class="container h-100 px-0">
        <div class="suha-footer-nav h-100">
          <ul class="h-100 d-flex align-items-center justify-content-between ps-0">
            <li><a href=""><i class="lni lni-home"></i>PRODUK</a></li>
            <li><a href="keranjang.php"><i class="lni lni-shopping-basket"><span class="badge"><?php echo count($_SESSION['cart']); ?></span></i>KERANJANG</a></li>
            <li><a href="cara.php"><i class="fa fa-info"></i>TUTORIAL</a></li>
            <li><a href="tentang.php"><i class="lni lni-cog"></i>TENTANG KAMI</a></li>
          </ul>
        </div>
      </div>
    </div>
    <!-- All JavaScript Files-->
    <script src="js/bootstrap.bundle.min.js"></script>
    <script src="js/jquery.min.js"></script>
    <script src="js/waypoints.min.js"></script>
    <script src="js/jquery.easing.min.js"></script>
    <script src="js/owl.carousel.min.js"></script>
    <script src="js/jquery.counterup.min.js"></script>
    <script src="js/jquery.countdown.min.js"></script>
    <script src="js/default/jquery.passwordstrength.js"></script>
    <script src="js/default/dark-mode-switch.js"></script>
    <script src="js/default/no-internet.js"></script>
    <script src="js/default/active.js"></script>
    <script src="js/pwa.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>